import type { DashboardOeeEmpresaData } from '../types'

export const DASHBOARD_OEE_EMPRESA_DATA: DashboardOeeEmpresaData = {
  rotuloDashboard: 'Dashboard OEE',
  tituloLinha: 'TOTAL EMPRESA',
  periodo: {
    inicio: '08/02/2026',
    fim: '14/02/2026',
  },
  oeeGlobal: {
    percentual: 53.66,
    descricao: '301 horas com produção > zero registradas no período',
  },
  indicadoresHero: [
    {
      id: 'envazado',
      titulo: 'Envazado',
      valor: 11439228,
      unidade: 'un',
      cor: '#00a870',
      fundo: 'rgba(0,168,112,0.08)',
      borda: 'rgba(0,168,112,0.2)',
    },
    {
      id: 'embalado',
      titulo: 'Embalado',
      valor: 12407821,
      unidade: 'un',
      cor: '#0075d4',
      fundo: 'rgba(0,117,212,0.08)',
      borda: 'rgba(0,117,212,0.2)',
    },
  ],
  ring: {
    arcos: [
      {
        id: 'oee',
        nome: 'OEE',
        percentual: 53.66,
        cor: '#00a870',
        raio: 80,
      },
      {
        id: 'disponibilidade',
        nome: 'Disponibilidade',
        percentual: 64.45,
        cor: '#0075d4',
        raio: 62,
      },
      {
        id: 'performance',
        nome: 'Performance',
        percentual: 83.51,
        cor: '#7c3aed',
        raio: 44,
      },
    ],
    legenda: [
      {
        id: 'oee',
        nome: 'OEE',
        percentual: 53.66,
        cor: '#00a870',
      },
      {
        id: 'disponibilidade',
        nome: 'Disponibilidade',
        percentual: 64.45,
        cor: '#0075d4',
      },
      {
        id: 'performance',
        nome: 'Performance',
        percentual: 83.51,
        cor: '#7c3aed',
      },
      {
        id: 'qualidade',
        nome: 'Qualidade',
        percentual: 99.7,
        cor: '#059669',
      },
    ],
  },
  kpis: [
    {
      id: 'disponibilidade',
      nome: 'Disponibilidade',
      percentual: 64.45,
      subtitulo: 'Horas disponíveis: 339:11 h',
      cor: '#0097ff',
    },
    {
      id: 'performance',
      nome: 'Performance',
      percentual: 83.51,
      subtitulo: 'Horas trabalhadas: 219:54 h',
      cor: '#a78bfa',
    },
    {
      id: 'qualidade',
      nome: 'Qualidade',
      percentual: 99.7,
      subtitulo: 'Perdas totais: 69.036 un',
      cor: '#34d399',
    },
  ],
  distribuicaoHoras: [
    {
      id: 'trabalhadas',
      valor: '219:54h',
      larguraPercentual: 39.6,
      gradiente: 'linear-gradient(90deg,#0075d4,#0053a0)',
      corTexto: '#ffffff',
      legenda: 'Horas Trabalhadas (219:54)',
      corLegenda: '#0075d4',
    },
    {
      id: 'indisponiveis',
      valor: '120:17h',
      larguraPercentual: 21.6,
      gradiente: 'linear-gradient(90deg,#e05a20,#b84010)',
      corTexto: '#ffffff',
      legenda: 'Paradas Indisponíveis (120:17)',
      corLegenda: '#e05a20',
    },
    {
      id: 'estrategicas',
      valor: '216:49h',
      larguraPercentual: 38.8,
      gradiente: 'linear-gradient(90deg,#d1d5db,#b0b7c2)',
      corTexto: '#6b7280',
      legenda: 'Paradas Estratégicas (216:49)',
      corLegenda: '#d1d5db',
      bordaLegenda: '#b0b7c2',
    },
  ],
  horasPeriodo: [
    {
      id: 'horas-disponiveis',
      rotulo: 'Horas Disponíveis',
      valor: '339:11',
      cor: '#0097ff',
    },
    {
      id: 'horas-trabalhadas',
      rotulo: 'Horas Trabalhadas',
      valor: '219:54',
      cor: '#e8ecf0',
    },
    {
      id: 'paradas-indisponiveis',
      rotulo: 'Paradas Indisponíveis',
      valor: '120:17',
      cor: '#ff6b35',
    },
    {
      id: 'paradas-estrategicas',
      rotulo: 'Paradas Estratégicas',
      valor: '216:49',
      cor: '#6b7280',
    },
  ],
  producao: [
    {
      id: 'envazado',
      titulo: 'Envazado',
      subtitulo: 'Unidades processadas',
      valor: 11439228,
      unidade: 'unidades',
      corValor: 'var(--accent)',
    },
    {
      id: 'embalado',
      titulo: 'Embalado',
      subtitulo: 'Unidades embaladas',
      valor: 12407821,
      unidade: 'unidades',
      corValor: 'var(--accent2)',
    },
    {
      id: 'horas-producao',
      titulo: 'Horas com produção',
      subtitulo: 'Produção > zero',
      valor: '301:00',
      unidade: 'horas',
    },
  ],
  perdas: [
    {
      id: 'perdas-envase',
      titulo: 'Perdas no Envase',
      subtitulo: 'Unidades não conformes',
      valor: 17295,
      corValor: 'var(--accent3)',
      badge: 'ENVASE',
    },
    {
      id: 'perdas-embalagem',
      titulo: 'Perdas na Embalagem',
      subtitulo: 'Unidades não conformes',
      valor: 51741,
      corValor: 'var(--accent3)',
      badge: 'EMBALAGEM',
    },
    {
      id: 'perdas-total',
      titulo: 'Total de Perdas',
      subtitulo: 'Impacto na qualidade: 0,30%',
      valor: 69036,
      corValor: 'var(--warn)',
      unidade: 'unidades',
    },
  ],
}
