-- =====================================================
-- Sistema OEE - SicFar | Farmace
-- Solicite informações sobre as políticas de RLS para cada tabela quando precisar consultar se existe alguma regra de negócio que possa afetar o acesso aos dados.