-- =====================================================
-- Sistema OEE - SicFar | Farmace
-- Script: 09-tboee-snapshot.sql
-- Descrição: Tabela de snapshot histórico de OEE
-- Versão: 1.0
-- Data: 2025-11-16
-- =====================================================

-- IMPORTANTE: Esta tabela implementa a estratégia de SNAPSHOT
-- Cada registro armazena TODOS os dados necessários para calcular OEE
-- de forma independente, garantindo rastreabilidade total (ALCOA+)

-- =====================================================
-- TBOEE - Snapshot Histórico de OEE
-- =====================================================

CREATE TABLE IF NOT EXISTS tboee (
  oee_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  -- ========================================
  -- DIMENSÕES (Chaves de Contexto)
  -- ========================================
  linhaproducao_id INTEGER NOT NULL REFERENCES tblinhaproducao(linhaproducao_id),
  lote_id INTEGER NULL,  -- FK para tblote (quando existir)
  produto_id INTEGER NOT NULL REFERENCES tbproduto(produto_id),
  turno_id INTEGER NULL REFERENCES tbturno(turno_id),
  departamento_id INTEGER NOT NULL REFERENCES tbdepartamento(departamento_id),

  -- Data/hora de referência do cálculo
  data_referencia DATE NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fim TIME NULL,  -- NULL se ainda em andamento

  -- ========================================
  -- SNAPSHOT DE PARÂMETROS (ALCOA+ - Original)
  -- Estes valores são "congelados" no momento do apontamento
  -- ========================================

  -- Velocidade nominal VIGENTE na data (snapshot)
  velocidade_nominal NUMERIC(10,2) NOT NULL,
  velocidade_fonte TEXT NULL,  -- Origem: 'CADASTRO', 'MANUAL', 'CLP'

  -- Meta OEE VIGENTE na data (snapshot)
  meta_oee NUMERIC(5,2) NULL,

  -- ========================================
  -- TEMPOS (em minutos)
  -- Todos armazenados para permitir validação e recálculo
  -- ========================================

  -- Tempo total do período
  tempo_calendario_minutos INTEGER NOT NULL CHECK (tempo_calendario_minutos >= 0),

  -- Paradas estratégicas (NÃO entram no tempo disponível)
  tempo_paradas_estrategicas_minutos INTEGER DEFAULT 0 CHECK (tempo_paradas_estrategicas_minutos >= 0),

  -- Tempo disponível = Calendário - Estratégicas
  tempo_disponivel_minutos INTEGER GENERATED ALWAYS AS (
    tempo_calendario_minutos - tempo_paradas_estrategicas_minutos
  ) STORED,

  -- Paradas planejadas (setup, manutenção preventiva)
  tempo_paradas_planejadas_minutos INTEGER DEFAULT 0 CHECK (tempo_paradas_planejadas_minutos >= 0),

  -- Paradas não planejadas (quebras, falta de insumo)
  tempo_paradas_nao_planejadas_minutos INTEGER DEFAULT 0 CHECK (tempo_paradas_nao_planejadas_minutos >= 0),

  -- Tempo de operação = Disponível - Planejadas - Não Planejadas
  tempo_operacao_minutos INTEGER GENERATED ALWAYS AS (
    tempo_calendario_minutos
    - tempo_paradas_estrategicas_minutos
    - tempo_paradas_planejadas_minutos
    - tempo_paradas_nao_planejadas_minutos
  ) STORED,

  -- Pequenas paradas (< 10 min, afetam Performance, não Disponibilidade)
  tempo_pequenas_paradas_minutos INTEGER DEFAULT 0 CHECK (tempo_pequenas_paradas_minutos >= 0),

  -- Tempo operacional líquido = Operação - Pequenas Paradas
  tempo_operacional_liquido_minutos INTEGER GENERATED ALWAYS AS (
    GREATEST(0,
      tempo_calendario_minutos
      - tempo_paradas_estrategicas_minutos
      - tempo_paradas_planejadas_minutos
      - tempo_paradas_nao_planejadas_minutos
      - tempo_pequenas_paradas_minutos
    )
  ) STORED,

  -- Tempo de retrabalho (afeta Qualidade)
  tempo_retrabalho_minutos INTEGER DEFAULT 0 CHECK (tempo_retrabalho_minutos >= 0),

  -- Tempo valioso = Op. Líquido - Retrabalho
  tempo_valioso_minutos INTEGER GENERATED ALWAYS AS (
    GREATEST(0,
      tempo_calendario_minutos
      - tempo_paradas_estrategicas_minutos
      - tempo_paradas_planejadas_minutos
      - tempo_paradas_nao_planejadas_minutos
      - tempo_pequenas_paradas_minutos
      - tempo_retrabalho_minutos
    )
  ) STORED,

  -- ========================================
  -- UNIDADES (Produção e Qualidade)
  -- ========================================

  unidades_produzidas INTEGER NOT NULL DEFAULT 0 CHECK (unidades_produzidas >= 0),
  unidades_boas INTEGER NOT NULL DEFAULT 0 CHECK (unidades_boas >= 0),
  unidades_refugadas INTEGER DEFAULT 0 CHECK (unidades_refugadas >= 0),
  unidades_retrabalhadas INTEGER DEFAULT 0 CHECK (unidades_retrabalhadas >= 0),

  -- ========================================
  -- COMPONENTES DO OEE (%)
  -- Calculados e armazenados para auditoria
  -- ========================================

  -- Disponibilidade = (Tempo Operação / Tempo Disponível) × 100
  disponibilidade NUMERIC(5,2) GENERATED ALWAYS AS (
    CASE
      WHEN (tempo_calendario_minutos - tempo_paradas_estrategicas_minutos) = 0 THEN 0
      ELSE ROUND(
        (tempo_calendario_minutos
         - tempo_paradas_estrategicas_minutos
         - tempo_paradas_planejadas_minutos
         - tempo_paradas_nao_planejadas_minutos
        )::NUMERIC
        / NULLIF(tempo_calendario_minutos - tempo_paradas_estrategicas_minutos, 0)
        * 100,
        2
      )
    END
  ) STORED,

  -- Performance = (Tempo Op. Líquido / Tempo Operação) × 100
  performance NUMERIC(5,2) GENERATED ALWAYS AS (
    CASE
      WHEN (tempo_calendario_minutos
            - tempo_paradas_estrategicas_minutos
            - tempo_paradas_planejadas_minutos
            - tempo_paradas_nao_planejadas_minutos) = 0 THEN 0
      ELSE ROUND(
        (tempo_calendario_minutos
         - tempo_paradas_estrategicas_minutos
         - tempo_paradas_planejadas_minutos
         - tempo_paradas_nao_planejadas_minutos
         - tempo_pequenas_paradas_minutos
        )::NUMERIC
        / NULLIF(
          tempo_calendario_minutos
          - tempo_paradas_estrategicas_minutos
          - tempo_paradas_planejadas_minutos
          - tempo_paradas_nao_planejadas_minutos,
          0
        )
        * 100,
        2
      )
    END
  ) STORED,

  -- Qualidade Unidades = (Unidades Boas / Unidades Produzidas) × 100
  qualidade_unidades NUMERIC(5,2) GENERATED ALWAYS AS (
    CASE
      WHEN unidades_produzidas = 0 THEN 100
      ELSE ROUND(
        unidades_boas::NUMERIC / NULLIF(unidades_produzidas, 0) * 100,
        2
      )
    END
  ) STORED,

  -- Qualidade Retrabalho = ((Tempo Op - Tempo Retrabalho) / Tempo Op) × 100
  qualidade_retrabalho NUMERIC(5,2) GENERATED ALWAYS AS (
    CASE
      WHEN (tempo_calendario_minutos
            - tempo_paradas_estrategicas_minutos
            - tempo_paradas_planejadas_minutos
            - tempo_paradas_nao_planejadas_minutos) = 0 THEN 100
      ELSE ROUND(
        (tempo_calendario_minutos
         - tempo_paradas_estrategicas_minutos
         - tempo_paradas_planejadas_minutos
         - tempo_paradas_nao_planejadas_minutos
         - tempo_retrabalho_minutos
        )::NUMERIC
        / NULLIF(
          tempo_calendario_minutos
          - tempo_paradas_estrategicas_minutos
          - tempo_paradas_planejadas_minutos
          - tempo_paradas_nao_planejadas_minutos,
          0
        )
        * 100,
        2
      )
    END
  ) STORED,

  -- Qualidade Total = Qualidade_Unidades × Qualidade_Retrabalho / 100
  qualidade NUMERIC(5,2) GENERATED ALWAYS AS (
    ROUND(
      (CASE
        WHEN unidades_produzidas = 0 THEN 100
        ELSE ROUND(
          unidades_boas::NUMERIC / NULLIF(unidades_produzidas, 0) * 100,
          2
        )
      END
      *
      CASE
        WHEN (tempo_calendario_minutos
              - tempo_paradas_estrategicas_minutos
              - tempo_paradas_planejadas_minutos
              - tempo_paradas_nao_planejadas_minutos) = 0 THEN 100
        ELSE ROUND(
          (tempo_calendario_minutos
           - tempo_paradas_estrategicas_minutos
           - tempo_paradas_planejadas_minutos
           - tempo_paradas_nao_planejadas_minutos
           - tempo_retrabalho_minutos
          )::NUMERIC
          / NULLIF(
            tempo_calendario_minutos
            - tempo_paradas_estrategicas_minutos
            - tempo_paradas_planejadas_minutos
            - tempo_paradas_nao_planejadas_minutos,
            0
          )
          * 100,
          2
        )
      END) / 100,
      2
    )
  ) STORED,

  -- OEE Final = Disponibilidade × Performance × Qualidade / 10000
  oee NUMERIC(5,2) GENERATED ALWAYS AS (
    ROUND(
      (
        -- Disponibilidade
        CASE
          WHEN (tempo_calendario_minutos - tempo_paradas_estrategicas_minutos) = 0 THEN 0
          ELSE ROUND(
            (tempo_calendario_minutos
             - tempo_paradas_estrategicas_minutos
             - tempo_paradas_planejadas_minutos
             - tempo_paradas_nao_planejadas_minutos
            )::NUMERIC
            / NULLIF(tempo_calendario_minutos - tempo_paradas_estrategicas_minutos, 0)
            * 100,
            2
          )
        END
        *
        -- Performance
        CASE
          WHEN (tempo_calendario_minutos
                - tempo_paradas_estrategicas_minutos
                - tempo_paradas_planejadas_minutos
                - tempo_paradas_nao_planejadas_minutos) = 0 THEN 0
          ELSE ROUND(
            (tempo_calendario_minutos
             - tempo_paradas_estrategicas_minutos
             - tempo_paradas_planejadas_minutos
             - tempo_paradas_nao_planejadas_minutos
             - tempo_pequenas_paradas_minutos
            )::NUMERIC
            / NULLIF(
              tempo_calendario_minutos
              - tempo_paradas_estrategicas_minutos
              - tempo_paradas_planejadas_minutos
              - tempo_paradas_nao_planejadas_minutos,
              0
            )
            * 100,
            2
          )
        END
        *
        -- Qualidade
        ROUND(
          (CASE
            WHEN unidades_produzidas = 0 THEN 100
            ELSE ROUND(
              unidades_boas::NUMERIC / NULLIF(unidades_produzidas, 0) * 100,
              2
            )
          END
          *
          CASE
            WHEN (tempo_calendario_minutos
                  - tempo_paradas_estrategicas_minutos
                  - tempo_paradas_planejadas_minutos
                  - tempo_paradas_nao_planejadas_minutos) = 0 THEN 100
            ELSE ROUND(
              (tempo_calendario_minutos
               - tempo_paradas_estrategicas_minutos
               - tempo_paradas_planejadas_minutos
               - tempo_paradas_nao_planejadas_minutos
               - tempo_retrabalho_minutos
              )::NUMERIC
              / NULLIF(
                tempo_calendario_minutos
                - tempo_paradas_estrategicas_minutos
                - tempo_paradas_planejadas_minutos
                - tempo_paradas_nao_planejadas_minutos,
                0
              )
              * 100,
              2
            )
          END) / 100,
          2
        )
      ) / 10000,
      2
    )
  ) STORED,

  -- Atingiu meta?
  atingiu_meta BOOLEAN GENERATED ALWAYS AS (
    CASE
      WHEN meta_oee IS NULL THEN NULL
      ELSE ROUND(
        (
          -- (cópia da fórmula de oee acima)
          CASE
            WHEN (tempo_calendario_minutos - tempo_paradas_estrategicas_minutos) = 0 THEN 0
            ELSE ROUND(
              (tempo_calendario_minutos
               - tempo_paradas_estrategicas_minutos
               - tempo_paradas_planejadas_minutos
               - tempo_paradas_nao_planejadas_minutos
              )::NUMERIC
              / NULLIF(tempo_calendario_minutos - tempo_paradas_estrategicas_minutos, 0)
              * 100,
              2
            )
          END
          *
          CASE
            WHEN (tempo_calendario_minutos
                  - tempo_paradas_estrategicas_minutos
                  - tempo_paradas_planejadas_minutos
                  - tempo_paradas_nao_planejadas_minutos) = 0 THEN 0
            ELSE ROUND(
              (tempo_calendario_minutos
               - tempo_paradas_estrategicas_minutos
               - tempo_paradas_planejadas_minutos
               - tempo_paradas_nao_planejadas_minutos
               - tempo_pequenas_paradas_minutos
              )::NUMERIC
              / NULLIF(
                tempo_calendario_minutos
                - tempo_paradas_estrategicas_minutos
                - tempo_paradas_planejadas_minutos
                - tempo_paradas_nao_planejadas_minutos,
                0
              )
              * 100,
              2
            )
          END
          *
          ROUND(
            (CASE
              WHEN unidades_produzidas = 0 THEN 100
              ELSE ROUND(
                unidades_boas::NUMERIC / NULLIF(unidades_produzidas, 0) * 100,
                2
              )
            END
            *
            CASE
              WHEN (tempo_calendario_minutos
                    - tempo_paradas_estrategicas_minutos
                    - tempo_paradas_planejadas_minutos
                    - tempo_paradas_nao_planejadas_minutos) = 0 THEN 100
              ELSE ROUND(
                (tempo_calendario_minutos
                 - tempo_paradas_estrategicas_minutos
                 - tempo_paradas_planejadas_minutos
                 - tempo_paradas_nao_planejadas_minutos
                 - tempo_retrabalho_minutos
                )::NUMERIC
                / NULLIF(
                  tempo_calendario_minutos
                  - tempo_paradas_estrategicas_minutos
                  - tempo_paradas_planejadas_minutos
                  - tempo_paradas_nao_planejadas_minutos,
                  0
                )
                * 100,
                2
              )
            END) / 100,
            2
          )
        ) / 10000,
        2
      ) >= meta_oee
    END
  ) STORED,

  -- ========================================
  -- METADADOS E RASTREABILIDADE (ALCOA+)
  -- ========================================

  -- Origem do cálculo
  calculo_tipo TEXT NOT NULL DEFAULT 'AUTOMATICO',  -- AUTOMATICO, MANUAL, RECALCULADO
  calculo_observacao TEXT NULL,

  -- Quando foi calculado (contemporâneo)
  calculado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'America/Fortaleza'),
  calculado_por INTEGER NULL REFERENCES tbusuario(usuario_id),

  -- Status do registro
  status TEXT NOT NULL DEFAULT 'ATIVO',  -- ATIVO, INVALIDADO, CORRIGIDO
  invalidado_em TIMESTAMP WITH TIME ZONE NULL,
  invalidado_por INTEGER NULL REFERENCES tbusuario(usuario_id),
  invalidado_motivo TEXT NULL,

  -- Vínculo com registro que corrigiu este (se houver)
  corrigido_por_oee_id INTEGER NULL REFERENCES tboee(oee_id),

  deletado TEXT NULL DEFAULT 'N',

  -- Integração com TOTVS/SICFAR
  sync TEXT NULL DEFAULT 'N',
  sync_data TIMESTAMP WITHOUT TIME ZONE NULL,

  -- Auditoria básica do registro (ALCOA+)
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'America/Fortaleza'),
  created_by INTEGER NULL REFERENCES tbusuario(usuario_id),
  updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
  updated_by INTEGER NULL REFERENCES tbusuario(usuario_id),
  deleted_at TIMESTAMP WITHOUT TIME ZONE NULL,
  deleted_by INTEGER NULL REFERENCES tbusuario(usuario_id),

  -- ========================================
  -- CONSTRAINTS
  -- ========================================

  CONSTRAINT tboee_pkey PRIMARY KEY (oee_id),

  -- Validação: unidades boas <= produzidas
  CONSTRAINT ck_unidades_boas CHECK (unidades_boas <= unidades_produzidas),

  -- Validação: refugadas + retrabalhadas <= produzidas
  CONSTRAINT ck_unidades_perdas CHECK (
    (unidades_refugadas + unidades_retrabalhadas) <= unidades_produzidas
  ),

  -- Validação: hora_fim >= hora_inicio
  CONSTRAINT ck_horario_oee CHECK (hora_fim IS NULL OR hora_fim >= hora_inicio),

  -- Índice único para evitar duplicatas (linha + data + turno + hora_inicio)
  CONSTRAINT uq_oee_periodo UNIQUE (
    linhaproducao_id,
    data_referencia,
    turno_id,
    hora_inicio
  )
);

-- ========================================
-- COMENTÁRIOS
-- ========================================

COMMENT ON TABLE tboee IS 'Snapshot histórico de OEE. Cada registro é IMUTÁVEL e contém todos os dados necessários para cálculo independente (ALCOA+)';

COMMENT ON COLUMN tboee.oee_id IS 'ID único do snapshot de OEE';
COMMENT ON COLUMN tboee.velocidade_nominal IS 'Snapshot da velocidade nominal VIGENTE na data_referencia';
COMMENT ON COLUMN tboee.meta_oee IS 'Snapshot da meta OEE VIGENTE na data_referencia';
COMMENT ON COLUMN tboee.tempo_calendario_minutos IS 'Tempo total do período em minutos';
COMMENT ON COLUMN tboee.calculo_tipo IS 'AUTOMATICO (trigger), MANUAL (inserção direta), RECALCULADO (correção)';
COMMENT ON COLUMN tboee.status IS 'ATIVO (válido), INVALIDADO (desconsiderar), CORRIGIDO (substituído por outro)';
COMMENT ON COLUMN tboee.corrigido_por_oee_id IS 'FK para registro que corrigiu este (se status=CORRIGIDO)';

-- ========================================
-- ÍNDICES PARA PERFORMANCE
-- ========================================

CREATE INDEX IF NOT EXISTS idx_tboee_linha_data ON tboee(linhaproducao_id, data_referencia);
CREATE INDEX IF NOT EXISTS idx_tboee_departamento_data ON tboee(departamento_id, data_referencia);
CREATE INDEX IF NOT EXISTS idx_tboee_produto ON tboee(produto_id);
CREATE INDEX IF NOT EXISTS idx_tboee_turno ON tboee(turno_id);
CREATE INDEX IF NOT EXISTS idx_tboee_lote ON tboee(lote_id);
CREATE INDEX IF NOT EXISTS idx_tboee_status ON tboee(status) WHERE status = 'ATIVO';
CREATE INDEX IF NOT EXISTS idx_tboee_calculado_em ON tboee(calculado_em);
CREATE INDEX IF NOT EXISTS idx_tboee_atingiu_meta ON tboee(atingiu_meta) WHERE atingiu_meta IS NOT NULL;

-- ========================================
-- REGRA: APPEND-ONLY (Imutabilidade)
-- ========================================
-- Para garantir ALCOA+ (Original, Durável), a tabela é append-only
-- Não permitir UPDATE nem DELETE direto

CREATE OR REPLACE RULE tboee_no_update AS
  ON UPDATE TO tboee
  DO INSTEAD NOTHING;

CREATE OR REPLACE RULE tboee_no_delete AS
  ON DELETE TO tboee
  DO INSTEAD NOTHING;

COMMENT ON RULE tboee_no_update ON tboee IS 'Tabela APPEND-ONLY: Updates devem ser feitos via invalidação + novo registro';
COMMENT ON RULE tboee_no_delete ON tboee IS 'Tabela APPEND-ONLY: Deletes devem ser feitos via campo status=INVALIDADO';

-- ========================================
-- FIM DO SCRIPT
-- ========================================
