-- =====================================================
-- Sistema OEE - SicFar | Farmace
-- Script: 11-tboee-parada.sql
-- Descrição: Tabela de Cadastro de Paradas para OEE
-- Versão: 1.0
-- Data: 2026-01-26
-- =====================================================

-- Esta tabela armazena os tipos de paradas que podem ser
-- registradas durante o apontamento de OEE. Cada parada
-- afeta um componente específico do cálculo de OEE
-- (Disponibilidade, Performance ou Qualidade).

-- =====================================================
-- ESTRUTURA DA TABELA
-- =====================================================

CREATE TABLE IF NOT EXISTS public.tboee_parada (
  -- Chave primária auto-incrementada
  oeeparada_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  -- Código único da parada (obrigatório)
  codigo TEXT NOT NULL,

  -- Classificação da parada
  componente TEXT NULL,    -- 'Disponibilidade', 'Performance' ou 'Qualidade'
  classe TEXT NULL,        -- 'Planejada', 'Não Planejada' ou 'Estratégica'
  natureza TEXT NULL,      -- Ex: 'Mecânica', 'Elétrica', 'Setup', etc.

  -- Identificação da parada
  parada TEXT NULL,        -- Nome/descrição curta
  descricao TEXT NULL,     -- Descrição detalhada

  -- Auditoria (ALCOA+)
  created_at TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT (now() AT TIME ZONE 'America/Fortaleza'::text),
  created_by UUID NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
  updated_by UUID NULL,
  deleted_at TIMESTAMP WITHOUT TIME ZONE NULL,
  deleted_by UUID NULL,

  -- Soft delete flag
  deletado public.deletado NULL DEFAULT 'N',

  -- Constraints
  CONSTRAINT tboee_parada_pkey PRIMARY KEY (oeeparada_id),
  CONSTRAINT tboee_parada_oeeparada_id_key UNIQUE (oeeparada_id),

  -- Foreign keys para auth.users (Supabase Auth)
  CONSTRAINT tboee_parada_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users (id),
  CONSTRAINT tboee_parada_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users (id),
  CONSTRAINT tboee_parada_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES auth.users (id)
) TABLESPACE pg_default;

-- Comentários da tabela
COMMENT ON TABLE public.tboee_parada IS 'Cadastro de tipos de paradas para cálculo de OEE';
COMMENT ON COLUMN public.tboee_parada.oeeparada_id IS 'ID único auto-incrementado';
COMMENT ON COLUMN public.tboee_parada.codigo IS 'Código da parada (obrigatório, ex: P001, PAR-001)';
COMMENT ON COLUMN public.tboee_parada.componente IS 'Componente OEE afetado: Disponibilidade, Performance ou Qualidade';
COMMENT ON COLUMN public.tboee_parada.classe IS 'Classificação: Planejada, Não Planejada ou Estratégica';
COMMENT ON COLUMN public.tboee_parada.natureza IS 'Natureza/origem: Mecânica, Elétrica, Setup, etc.';
COMMENT ON COLUMN public.tboee_parada.parada IS 'Nome/descrição curta da parada';
COMMENT ON COLUMN public.tboee_parada.descricao IS 'Descrição detalhada do tipo de parada';
COMMENT ON COLUMN public.tboee_parada.deletado IS 'Flag de exclusão lógica: S=excluído, N=ativo';

-- =====================================================
-- ÍNDICES PARA PERFORMANCE
-- =====================================================

-- Índice para busca por código
CREATE INDEX IF NOT EXISTS idx_tboee_parada_codigo
  ON public.tboee_parada(codigo);

-- Índice para filtro por componente OEE
CREATE INDEX IF NOT EXISTS idx_tboee_parada_componente
  ON public.tboee_parada(componente)
  WHERE deletado = 'N';

-- Índice para filtro por classe
CREATE INDEX IF NOT EXISTS idx_tboee_parada_classe
  ON public.tboee_parada(classe)
  WHERE deletado = 'N';

-- Índice para listagem de ativos
CREATE INDEX IF NOT EXISTS idx_tboee_parada_deletado
  ON public.tboee_parada(deletado);

-- =====================================================
-- ROW LEVEL SECURITY (RLS)
-- =====================================================

-- Habilitar RLS na tabela
ALTER TABLE public.tboee_parada ENABLE ROW LEVEL SECURITY;

-- Política de leitura: todos autenticados podem ler
CREATE POLICY "ler" ON public.tboee_parada
  FOR SELECT
  TO authenticated
  USING (true);

-- Política de inserção: todos autenticados podem inserir
CREATE POLICY "Inserir" ON public.tboee_parada
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Política de edição: todos autenticados podem editar
CREATE POLICY "Editar" ON public.tboee_parada
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- =====================================================
-- REGRAS DE NEGÓCIO
-- =====================================================

/*
CLASSIFICAÇÃO DE PARADAS E IMPACTO NO OEE:

1. CLASSE DA PARADA:
   - Planejada: Paradas previstas no planejamento (manutenção preventiva, setup, etc.)
   - Não Planejada: Paradas não previstas (quebras, falhas, etc.)
   - Estratégica: NÃO entram no cálculo do OEE (são excluídas do tempo disponível)

2. COMPONENTE OEE AFETADO:
   - Disponibilidade: Paradas que afetam o tempo de operação (> 10 min)
   - Performance: Pequenas paradas (< 10 min) e reduções de velocidade
   - Qualidade: Perdas por refugo, retrabalho, etc.

3. REGRA DOS 10 MINUTOS:
   - Paradas menores que 10 minutos afetam PERFORMANCE, não Disponibilidade
   - Paradas iguais ou maiores que 10 minutos afetam DISPONIBILIDADE

4. CÁLCULO DO OEE:
   OEE = Disponibilidade × Performance × Qualidade

   Onde:
   - Disponibilidade = (Tempo de Operação / Tempo Disponível) × 100
   - Performance = (Tempo Operacional Líquido / Tempo de Operação) × 100
   - Qualidade = (Unidades Boas / Unidades Produzidas) × 100

   Tempo Disponível = Tempo Calendário - Paradas Estratégicas
*/

-- =====================================================
-- FIM DO SCRIPT
-- =====================================================
