-- =====================================================
-- Sistema OEE - SicFar | Farmace
-- Script: 13-tbrotina-tbperfil-rotina.sql
-- Descrição: Tabelas para controle de acesso por rotina (RBAC)
-- Versão: 1.0
-- Data: 2025-02-01
-- =====================================================

-- PRÉ-REQUISITO: Execute 02-tables.sql antes deste script

-- =====================================================
-- CONTROLE DE ACESSO BASEADO EM PERFIL E ROTINA (RBAC)
-- =====================================================

-- ----------------------------------------------------
-- TBROTINA
-- Cadastro de todas as rotinas/funcionalidades do sistema
-- ESTRUTURA JÁ EXISTENTE NO BANCO:
-- ----------------------------------------------------
-- create table public.tbrotina (
--   rotina_id integer generated by default as identity not null,
--   app_id integer not null,
--   rotina text not null,
--   rotulo text not null,
--   descricao text null,
--   modulo text not null,
--   ordem text not null,
--   created_at timestamp without time zone not null default (now() AT TIME ZONE 'America/Fortaleza'::text),
--   created_by uuid not null,
--   updated_at timestamp without time zone null,
--   updated_by uuid null,
--   deleted_at timestamp without time zone null,
--   deleted_by uuid null,
--   deletado public.deletado not null default 'N'::deletado,
--   constraint tbrotina_pkey primary key (rotina_id),
--   constraint tbrotina_rotina_id_key unique (rotina_id),
--   constraint tbrotina_app_id_fkey foreign KEY (app_id) references tbapp (app_id),
--   constraint tbrotina_created_by_fkey foreign KEY (created_by) references auth.users (id),
--   constraint tbrotina_deleted_by_fkey foreign KEY (deleted_by) references auth.users (id),
--   constraint tbrotina_updated_by_fkey foreign KEY (updated_by) references auth.users (id)
-- ) TABLESPACE pg_default;

-- ----------------------------------------------------
-- TBPERFIL_ROTINA
-- Matriz de permissões: define qual perfil tem acesso a qual rotina de qual aplicação
-- ESTRUTURA JÁ EXISTENTE NO BANCO:
-- ----------------------------------------------------
-- create table public.tbperfil_rotina (
--   perfilrotina_id bigint generated by default as identity not null,
--   app_id integer not null,
--   perfil_id integer not null,
--   rotina_id integer not null,
--   acesso public.acesso_rotina not null,
--   deletado public.deletado not null default 'N'::deletado,
--   created_at timestamp without time zone not null default (now() AT TIME ZONE 'America/Fortaleza'::text),
--   created_by uuid not null,
--   updated_at timestamp without time zone null,
--   updated_by uuid null,
--   deleted_at timestamp without time zone null,
--   deleted_by uuid null,
--   constraint tbperfil_rotina_pkey primary key (perfilrotina_id),
--   constraint tbperfil_rotina_perfilrotina_id_key unique (perfilrotina_id),
--   constraint tbperfil_rotina_deleted_by_fkey foreign KEY (deleted_by) references auth.users (id),
--   constraint tbperfil_rotina_perfil_id_fkey foreign KEY (perfil_id) references tbperfil (perfil_id),
--   constraint tbperfil_rotina_rotina_id_fkey foreign KEY (rotina_id) references tbrotina (rotina_id),
--   constraint tbperfil_rotina_app_id_fkey foreign KEY (app_id) references tbapp (app_id),
--   constraint tbperfil_rotina_updated_by_fkey foreign KEY (updated_by) references auth.users (id),
--   constraint tbperfil_rotina_created_by_fkey foreign KEY (created_by) references auth.users (id)
-- ) TABLESPACE pg_default;

-- =====================================================
-- HABILITAR RLS NAS TABELAS
-- =====================================================
ALTER TABLE tbrotina ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbperfil_rotina ENABLE ROW LEVEL SECURITY;

-- Políticas básicas (leitura para autenticados)
CREATE POLICY tbrotina_select_policy ON tbrotina
  FOR SELECT TO authenticated
  USING (deletado = 'N');

CREATE POLICY tbperfil_rotina_select_policy ON tbperfil_rotina
  FOR SELECT TO authenticated
  USING (deletado = 'N');

-- =====================================================
-- SEEDS: ROTINAS INICIAIS DO SISTEMA
-- =====================================================

-- Módulo: USUARIOS
INSERT INTO tbrotina (rotina, descricao, modulo, ordem) VALUES
  ('VISUALIZAR_USUARIO', 'Visualizar lista de usuários', 'USUARIOS', 1),
  ('CRIAR_USUARIO', 'Criar novo usuário', 'USUARIOS', 2),
  ('EDITAR_USUARIO', 'Editar dados de usuário', 'USUARIOS', 3),
  ('EXCLUIR_USUARIO', 'Excluir usuário (soft delete)', 'USUARIOS', 4),
  ('ALTERAR_PERFIL_USUARIO', 'Alterar perfil/permissões de usuário', 'USUARIOS', 5)
ON CONFLICT (rotina) DO NOTHING;

-- Módulo: FUNCIONARIOS
INSERT INTO tbrotina (rotina, descricao, modulo, ordem) VALUES
  ('VISUALIZAR_FUNCIONARIO', 'Visualizar lista de funcionários', 'FUNCIONARIOS', 1),
  ('CRIAR_FUNCIONARIO', 'Criar novo funcionário', 'FUNCIONARIOS', 2),
  ('EDITAR_FUNCIONARIO', 'Editar dados de funcionário', 'FUNCIONARIOS', 3),
  ('EXCLUIR_FUNCIONARIO', 'Excluir funcionário', 'FUNCIONARIOS', 4)
ON CONFLICT (rotina) DO NOTHING;

-- Módulo: PRODUCAO
INSERT INTO tbrotina (rotina, descricao, modulo, ordem) VALUES
  ('VISUALIZAR_LINHA', 'Visualizar linhas de produção', 'PRODUCAO', 1),
  ('CRIAR_LINHA', 'Criar nova linha de produção', 'PRODUCAO', 2),
  ('EDITAR_LINHA', 'Editar linha de produção', 'PRODUCAO', 3),
  ('EXCLUIR_LINHA', 'Excluir linha de produção', 'PRODUCAO', 4),
  ('VISUALIZAR_LOTE', 'Visualizar lotes de produção', 'PRODUCAO', 5),
  ('CRIAR_LOTE', 'Criar novo lote', 'PRODUCAO', 6),
  ('EDITAR_LOTE', 'Editar lote de produção', 'PRODUCAO', 7),
  ('EXCLUIR_LOTE', 'Excluir lote de produção', 'PRODUCAO', 8),
  ('CONCLUIR_LOTE', 'Concluir/fechar lote de produção', 'PRODUCAO', 9)
ON CONFLICT (rotina) DO NOTHING;

-- Módulo: APONTAMENTOS
INSERT INTO tbrotina (rotina, descricao, modulo, ordem) VALUES
  ('VISUALIZAR_APONTAMENTO', 'Visualizar apontamentos', 'APONTAMENTOS', 1),
  ('CRIAR_APONTAMENTO', 'Criar apontamento de parada/produção', 'APONTAMENTOS', 2),
  ('EDITAR_APONTAMENTO', 'Editar apontamento existente', 'APONTAMENTOS', 3),
  ('EXCLUIR_APONTAMENTO', 'Excluir apontamento', 'APONTAMENTOS', 4),
  ('ASSINAR_APONTAMENTO', 'Assinar/conferir apontamento (supervisor)', 'APONTAMENTOS', 5)
ON CONFLICT (rotina) DO NOTHING;

-- Módulo: PARADAS
INSERT INTO tbrotina (rotina, descricao, modulo, ordem) VALUES
  ('VISUALIZAR_MOTIVO_PARADA', 'Visualizar motivos de parada', 'PARADAS', 1),
  ('CRIAR_MOTIVO_PARADA', 'Criar novo motivo de parada', 'PARADAS', 2),
  ('EDITAR_MOTIVO_PARADA', 'Editar motivo de parada', 'PARADAS', 3),
  ('EXCLUIR_MOTIVO_PARADA', 'Excluir motivo de parada', 'PARADAS', 4)
ON CONFLICT (rotina) DO NOTHING;

-- Módulo: CONFIGURACOES
INSERT INTO tbrotina (rotina, descricao, modulo, ordem) VALUES
  ('VISUALIZAR_SETOR', 'Visualizar setores', 'CONFIGURACOES', 1),
  ('CRIAR_SETOR', 'Criar novo setor', 'CONFIGURACOES', 2),
  ('EDITAR_SETOR', 'Editar setor', 'CONFIGURACOES', 3),
  ('EXCLUIR_SETOR', 'Excluir setor', 'CONFIGURACOES', 4),
  ('VISUALIZAR_TURNO', 'Visualizar turnos', 'CONFIGURACOES', 5),
  ('CRIAR_TURNO', 'Criar novo turno', 'CONFIGURACOES', 6),
  ('EDITAR_TURNO', 'Editar turno', 'CONFIGURACOES', 7),
  ('EXCLUIR_TURNO', 'Excluir turno', 'CONFIGURACOES', 8),
  ('VISUALIZAR_PRODUTO', 'Visualizar produtos/SKUs', 'CONFIGURACOES', 9),
  ('CRIAR_PRODUTO', 'Criar novo produto', 'CONFIGURACOES', 10),
  ('EDITAR_PRODUTO', 'Editar produto', 'CONFIGURACOES', 11),
  ('EXCLUIR_PRODUTO', 'Excluir produto', 'CONFIGURACOES', 12),
  ('GERENCIAR_PERFIL', 'Gerenciar perfis de acesso', 'CONFIGURACOES', 13),
  ('GERENCIAR_PERMISSOES', 'Gerenciar permissões por perfil', 'CONFIGURACOES', 14)
ON CONFLICT (rotina) DO NOTHING;

-- Módulo: RELATORIOS
INSERT INTO tbrotina (rotina, descricao, modulo, ordem) VALUES
  ('VISUALIZAR_DASHBOARD', 'Visualizar dashboard OEE', 'RELATORIOS', 1),
  ('EXPORTAR_RELATORIO', 'Exportar relatórios (PDF/Excel)', 'RELATORIOS', 2),
  ('VISUALIZAR_HISTORICO', 'Visualizar histórico de OEE', 'RELATORIOS', 3)
ON CONFLICT (rotina) DO NOTHING;

-- =====================================================
-- SEEDS: PERMISSÕES PADRÃO POR PERFIL
-- =====================================================

-- Função auxiliar para inserir permissões em lote
-- CORRIGIDO: Removida coluna 'rotina' que não existe em tbperfil_rotina
CREATE OR REPLACE FUNCTION setup_perfil_permissions(
  p_app_id INTEGER,
  p_perfil_id INTEGER,
  p_rotinas TEXT[],
  p_acesso acesso_rotina DEFAULT 'S'
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_rotina RECORD;
BEGIN
  FOR v_rotina IN
    SELECT rotina_id
    FROM tbrotina
    WHERE rotina = ANY(p_rotinas)
      AND app_id = p_app_id
      AND deletado = 'N'
  LOOP
    INSERT INTO tbperfil_rotina (app_id, perfil_id, rotina_id, acesso, created_by)
    VALUES (p_app_id, p_perfil_id, v_rotina.rotina_id, p_acesso, auth.uid())
    ON CONFLICT ON CONSTRAINT tbperfil_rotina_pkey DO UPDATE SET
      acesso = p_acesso,
      updated_at = NOW(),
      updated_by = auth.uid();
  END LOOP;
END;
$$;

-- ADMINISTRADOR (perfil_id = 1): Acesso total
-- Parâmetros: app_id, perfil_id, rotinas[], acesso
SELECT setup_perfil_permissions(1, 1, ARRAY[
  -- Usuários
  'VISUALIZAR_USUARIO', 'CRIAR_USUARIO', 'EDITAR_USUARIO', 'EXCLUIR_USUARIO', 'ALTERAR_PERFIL_USUARIO',
  -- Funcionários
  'VISUALIZAR_FUNCIONARIO', 'CRIAR_FUNCIONARIO', 'EDITAR_FUNCIONARIO', 'EXCLUIR_FUNCIONARIO',
  -- Produção
  'VISUALIZAR_LINHA', 'CRIAR_LINHA', 'EDITAR_LINHA', 'EXCLUIR_LINHA',
  'VISUALIZAR_LOTE', 'CRIAR_LOTE', 'EDITAR_LOTE', 'EXCLUIR_LOTE', 'CONCLUIR_LOTE',
  -- Apontamentos
  'VISUALIZAR_APONTAMENTO', 'CRIAR_APONTAMENTO', 'EDITAR_APONTAMENTO', 'EXCLUIR_APONTAMENTO', 'ASSINAR_APONTAMENTO',
  -- Paradas
  'VISUALIZAR_MOTIVO_PARADA', 'CRIAR_MOTIVO_PARADA', 'EDITAR_MOTIVO_PARADA', 'EXCLUIR_MOTIVO_PARADA',
  -- Configurações
  'VISUALIZAR_SETOR', 'CRIAR_SETOR', 'EDITAR_SETOR', 'EXCLUIR_SETOR',
  'VISUALIZAR_TURNO', 'CRIAR_TURNO', 'EDITAR_TURNO', 'EXCLUIR_TURNO',
  'VISUALIZAR_PRODUTO', 'CRIAR_PRODUTO', 'EDITAR_PRODUTO', 'EXCLUIR_PRODUTO',
  'GERENCIAR_PERFIL', 'GERENCIAR_PERMISSOES',
  -- Relatórios
  'VISUALIZAR_DASHBOARD', 'EXPORTAR_RELATORIO', 'VISUALIZAR_HISTORICO'
], 'S');

-- SUPERVISOR (perfil_id = 2): Gestão operacional, sem configurações críticas
SELECT setup_perfil_permissions(1, 2, ARRAY[
  -- Usuários (apenas visualizar)
  'VISUALIZAR_USUARIO',
  -- Funcionários
  'VISUALIZAR_FUNCIONARIO', 'CRIAR_FUNCIONARIO', 'EDITAR_FUNCIONARIO',
  -- Produção
  'VISUALIZAR_LINHA', 'VISUALIZAR_LOTE', 'CRIAR_LOTE', 'EDITAR_LOTE', 'CONCLUIR_LOTE',
  -- Apontamentos (incluindo assinatura)
  'VISUALIZAR_APONTAMENTO', 'CRIAR_APONTAMENTO', 'EDITAR_APONTAMENTO', 'ASSINAR_APONTAMENTO',
  -- Paradas (apenas visualizar)
  'VISUALIZAR_MOTIVO_PARADA',
  -- Configurações (apenas visualizar)
  'VISUALIZAR_SETOR', 'VISUALIZAR_TURNO', 'VISUALIZAR_PRODUTO',
  -- Relatórios
  'VISUALIZAR_DASHBOARD', 'EXPORTAR_RELATORIO', 'VISUALIZAR_HISTORICO'
], 'S');

-- OPERADOR (perfil_id = 3): Apontamentos e consultas básicas
SELECT setup_perfil_permissions(1, 3, ARRAY[
  -- Produção (apenas visualizar)
  'VISUALIZAR_LINHA', 'VISUALIZAR_LOTE',
  -- Apontamentos (criar e visualizar)
  'VISUALIZAR_APONTAMENTO', 'CRIAR_APONTAMENTO',
  -- Paradas (apenas visualizar)
  'VISUALIZAR_MOTIVO_PARADA',
  -- Configurações (apenas visualizar)
  'VISUALIZAR_SETOR', 'VISUALIZAR_TURNO', 'VISUALIZAR_PRODUTO',
  -- Relatórios (apenas dashboard)
  'VISUALIZAR_DASHBOARD'
], 'S');

-- VISUALIZADOR (perfil_id = 4): Apenas visualização
SELECT setup_perfil_permissions(1, 4, ARRAY[
  -- Apenas visualizações
  'VISUALIZAR_USUARIO',
  'VISUALIZAR_FUNCIONARIO',
  'VISUALIZAR_LINHA', 'VISUALIZAR_LOTE',
  'VISUALIZAR_APONTAMENTO',
  'VISUALIZAR_MOTIVO_PARADA',
  'VISUALIZAR_SETOR', 'VISUALIZAR_TURNO', 'VISUALIZAR_PRODUTO',
  'VISUALIZAR_DASHBOARD', 'VISUALIZAR_HISTORICO'
], 'S');

-- Remover função auxiliar (opcional - pode manter para uso futuro)
-- DROP FUNCTION IF EXISTS setup_perfil_permissions;

-- =====================================================
-- FIM DO SCRIPT
-- =====================================================
-- Próximo script: 14-check-user-permission.sql
