-- =====================================================
-- Sistema OEE - SicFar | Farmace
-- Script: 16-rls-tbperfil.sql
-- Descrição: Políticas RLS para tabela tbperfil
-- Versão: 1.0
-- Data: 2025-02-01
-- =====================================================

-- PRÉ-REQUISITO: Execute 14-check-user-permission.sql antes deste script

-- =====================================================
-- ESTRUTURA DA TABELA TBPERFIL (Referência)
-- =====================================================
--
-- create table public.tbperfil (
--   perfil_id integer generated by default as identity not null,
--   perfil text not null,
--   observacao text null,
--   created_at timestamp without time zone not null default (now() AT TIME ZONE 'America/Fortaleza'::text),
--   created_by uuid not null,
--   updated_at timestamp without time zone null,
--   updated_by uuid null,
--   deleted_at timestamp without time zone null,
--   deleted_by uuid null,
--   deletado public.deletado not null default 'N'::deletado,
--   constraint tbperfil_pkey primary key (perfil_id),
--   constraint tbperfil_perfil_id_key unique (perfil_id),
--   constraint tbperfil_created_by_fkey foreign KEY (created_by) references auth.users (id),
--   constraint tbperfil_deleted_by_fkey foreign KEY (deleted_by) references auth.users (id),
--   constraint tbperfil_updated_by_fkey foreign KEY (updated_by) references auth.users (id)
-- ) TABLESPACE pg_default;
--
-- =====================================================

-- =====================================================
-- REGRAS DE NEGÓCIO PARA TBPERFIL
-- =====================================================
--
-- A tabela tbperfil armazena os perfis de acesso do sistema:
--   - Administrador (perfil_id = 1)
--   - Supervisor (perfil_id = 2)
--   - Operador (perfil_id = 3)
--   - Visualizador (perfil_id = 4)
--
-- REGRAS DE ACESSO:
--   SELECT: Todos os usuários autenticados podem visualizar
--           (necessário para popular dropdowns de seleção de perfil)
--
--   INSERT: Apenas Administradores podem criar novos perfis
--           (operação rara, geralmente feita apenas na implantação)
--
--   UPDATE: Apenas Administradores podem editar perfis
--           (alterar nome, observação, etc.)
--
--   DELETE: Apenas Administradores podem excluir perfis
--           (recomenda-se soft delete via deleted_at)
--
-- NOTA: Esta tabela NÃO usa o campo 'deletado' como VARCHAR.
--       Usa deleted_at como TIMESTAMP (NULL = ativo, NOT NULL = excluído)
--
-- =====================================================

-- Habilitar RLS na tabela
ALTER TABLE tbperfil ENABLE ROW LEVEL SECURITY;

-- Forçar RLS mesmo para o owner da tabela (segurança extra)
ALTER TABLE tbperfil FORCE ROW LEVEL SECURITY;

-- =====================================================
-- REMOVER POLÍTICAS EXISTENTES (se houver)
-- =====================================================
DROP POLICY IF EXISTS tbperfil_select_policy ON tbperfil;
DROP POLICY IF EXISTS tbperfil_insert_policy ON tbperfil;
DROP POLICY IF EXISTS tbperfil_update_policy ON tbperfil;
DROP POLICY IF EXISTS tbperfil_delete_policy ON tbperfil;

-- =====================================================
-- POLÍTICA DE SELECT (Leitura)
-- =====================================================
-- Quem pode ler: Todos os usuários autenticados
-- Condição: Apenas perfis não excluídos (deleted_at IS NULL)
-- Motivo: Necessário para popular dropdowns em formulários
-- =====================================================

CREATE POLICY tbperfil_select_policy ON tbperfil
  FOR SELECT
  TO authenticated
  USING (
    -- Apenas registros não excluídos
    deleted_at IS NULL
  );

COMMENT ON POLICY tbperfil_select_policy ON tbperfil IS
  'Permite que todos os usuários autenticados visualizem os perfis ativos.
   Necessário para popular dropdowns de seleção de perfil em formulários.';

-- =====================================================
-- POLÍTICA DE INSERT (Criação)
-- =====================================================
-- Quem pode criar: Apenas Administradores
-- Condição: Usuário deve ter perfil = Administrador ou perfil_id = 1
-- Motivo: Criação de perfis é operação administrativa crítica
-- =====================================================

CREATE POLICY tbperfil_insert_policy ON tbperfil
  FOR INSERT
  TO authenticated
  WITH CHECK (
    -- Apenas administradores podem criar perfis
    -- Usa a função is_admin() definida em 14-check-user-permission.sql
    is_admin()
  );

COMMENT ON POLICY tbperfil_insert_policy ON tbperfil IS
  'Permite que apenas Administradores criem novos perfis.
   Criação de perfis é uma operação administrativa crítica.';

-- =====================================================
-- POLÍTICA DE UPDATE (Atualização)
-- =====================================================
-- Quem pode editar: Apenas Administradores
-- Condição: Registro não pode estar excluído
-- Motivo: Alteração de perfis afeta permissões de múltiplos usuários
-- =====================================================

CREATE POLICY tbperfil_update_policy ON tbperfil
  FOR UPDATE
  TO authenticated
  USING (
    -- Só pode editar se não estiver excluído E for admin
    deleted_at IS NULL
    AND is_admin()
  )
  WITH CHECK (
    -- Validação adicional no novo valor
    is_admin()
  );

COMMENT ON POLICY tbperfil_update_policy ON tbperfil IS
  'Permite que apenas Administradores editem perfis existentes.
   Não permite editar perfis que já foram excluídos (soft delete).';

-- =====================================================
-- POLÍTICA DE DELETE (Exclusão)
-- =====================================================
-- Quem pode excluir: Apenas Administradores
-- Condição: Registro não pode já estar excluído
-- Recomendação: Usar soft delete (UPDATE deleted_at) ao invés de DELETE
-- Motivo: Manter histórico para auditoria (ALCOA+)
-- =====================================================

CREATE POLICY tbperfil_delete_policy ON tbperfil
  FOR DELETE
  TO authenticated
  USING (
    -- Só pode excluir se não estiver já excluído E for admin
    deleted_at IS NULL
    AND is_admin()
  );

COMMENT ON POLICY tbperfil_delete_policy ON tbperfil IS
  'Permite que apenas Administradores excluam perfis.
   RECOMENDAÇÃO: Usar soft delete (UPDATE deleted_at = NOW()) ao invés de DELETE
   para manter histórico de auditoria conforme ALCOA+.';

-- =====================================================
-- FUNÇÃO AUXILIAR: Soft Delete para tbperfil
-- =====================================================
-- Função para realizar soft delete mantendo auditoria ALCOA+

CREATE OR REPLACE FUNCTION soft_delete_perfil(p_perfil_id INTEGER)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Verificar se é administrador
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'Apenas administradores podem excluir perfis';
  END IF;

  -- Verificar se perfil existe e não está excluído
  IF NOT EXISTS (
    SELECT 1 FROM tbperfil
    WHERE perfil_id = p_perfil_id AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Perfil não encontrado ou já excluído';
  END IF;

  -- Verificar se há usuários usando este perfil
  IF EXISTS (
    SELECT 1 FROM tbusuario
    WHERE perfil_id = p_perfil_id AND deletado = 'N'
  ) THEN
    RAISE EXCEPTION 'Não é possível excluir perfil em uso por usuários ativos';
  END IF;

  -- Realizar soft delete
  UPDATE tbperfil
  SET
    deleted_at = NOW(),
    deleted_by = auth.uid(),
    updated_at = NOW(),
    updated_by = auth.uid()
  WHERE perfil_id = p_perfil_id;

  RETURN TRUE;
END;
$$;

COMMENT ON FUNCTION soft_delete_perfil(INTEGER) IS
  'Realiza soft delete de um perfil, verificando se não há usuários vinculados.
   Apenas administradores podem executar esta função.';

GRANT EXECUTE ON FUNCTION soft_delete_perfil(INTEGER) TO authenticated;

-- =====================================================
-- ÍNDICES PARA PERFORMANCE
-- =====================================================

-- Índice para consultas de perfis ativos
CREATE INDEX IF NOT EXISTS idx_tbperfil_active
  ON tbperfil(perfil_id)
  WHERE deleted_at IS NULL;

-- Índice para busca por nome de perfil
CREATE INDEX IF NOT EXISTS idx_tbperfil_nome
  ON tbperfil(perfil)
  WHERE deleted_at IS NULL;

-- =====================================================
-- GRANT DE PERMISSÕES
-- =====================================================

-- Garantir que authenticated pode acessar a tabela (RLS controla o resto)
GRANT SELECT, INSERT, UPDATE, DELETE ON tbperfil TO authenticated;

-- Garantir acesso à sequence do perfil_id
GRANT USAGE, SELECT ON SEQUENCE tbperfil_perfil_id_seq TO authenticated;

-- =====================================================
-- TESTES DE VALIDAÇÃO (Comentados - usar manualmente)
-- =====================================================

-- Para testar as políticas, execute como diferentes usuários:
--
-- -- Como Administrador (deve funcionar):
-- SELECT * FROM tbperfil;
-- INSERT INTO tbperfil (perfil, observacao) VALUES ('Teste', 'Perfil de teste');
-- UPDATE tbperfil SET observacao = 'Atualizado' WHERE perfil = 'Teste';
-- SELECT soft_delete_perfil((SELECT perfil_id FROM tbperfil WHERE perfil = 'Teste'));
--
-- -- Como Operador (SELECT deve funcionar, outros devem falhar):
-- SELECT * FROM tbperfil;  -- OK
-- INSERT INTO tbperfil (perfil) VALUES ('Hack'); -- ERRO: violates RLS policy
-- UPDATE tbperfil SET perfil = 'Hacked' WHERE perfil_id = 1; -- ERRO
-- DELETE FROM tbperfil WHERE perfil_id = 1; -- ERRO

-- =====================================================
-- RESUMO DAS POLÍTICAS
-- =====================================================
--
-- | Operação | Quem pode executar    | Condição adicional          |
-- |----------|----------------------|------------------------------|
-- | SELECT   | Todos autenticados   | deleted_at IS NULL           |
-- | INSERT   | Apenas Administrador | -                            |
-- | UPDATE   | Apenas Administrador | deleted_at IS NULL           |
-- | DELETE   | Apenas Administrador | deleted_at IS NULL           |
--
-- =====================================================
-- FIM DO SCRIPT
-- =====================================================
