-- =====================================================
-- Sistema OEE - SicFar | Farmace
-- Script: 18-multi-app-structure.sql
-- Descrição: Estrutura completa para sistema Multi-Aplicação
-- Versão: 1.0
-- Data: 2025-02-01
-- =====================================================

-- =====================================================
-- VISÃO GERAL DA ARQUITETURA MULTI-APP
-- =====================================================
--
--  tbusuario (GLOBAL - usuários únicos no sistema)
--      │
--      └──► tbusuario_app (N:N - usuário pode acessar várias apps)
--               │
--               ├── usuario_id (FK tbusuario)
--               ├── app_id (FK tbapp)
--               └── perfil_id (FK tbperfil) ← perfil do usuário NAQUELA app
--
--  tbapp (Aplicações do sistema)
--      │
--      ├──► tbperfil (perfis POR app) ← adicionar app_id
--      │
--      └──► tbrotina (rotinas POR app) ← adicionar app_id
--               │
--               └──► tbperfil_rotina (permissões perfil x rotina por app)
--
-- EXEMPLO:
--   - João é Administrador no SysOEE (app_id=1)
--   - João é Operador no SysRH (app_id=2)
--   - Maria só tem acesso ao SysOEE como Supervisora
--
-- =====================================================

-- =====================================================
-- PARTE 1: TABELA TBAPP (Referência)
-- =====================================================
-- Estrutura já existente no banco:
--
-- create table public.tbapp (  
--   app_id integer generated by default as identity not null,
--   app_nome text not null,
--   created_at timestamp without time zone not null default (now() AT TIME ZONE 'America/Fortaleza'::text),
--   created_by uuid null,
--   updated_at timestamp without time zone null,
--   updated_by uuid null,
--   deleted_at timestamp without time zone null,
--   deleted_by uuid null,
--   deletado public.deletado null default 'N'::deletado,
--   constraint tbapp_pkey primary key (app_id),
--   constraint tbapp_app_id_key unique (app_id),
--   constraint tbapp_created_by_fkey foreign KEY (created_by) references auth.users (id),
--   constraint tbapp_deleted_by_fkey foreign KEY (deleted_by) references auth.users (id),
--   constraint tbapp_updated_by_fkey foreign KEY (updated_by) references auth.users (id)
-- ) TABLESPACE pg_default;
--
-- =====================================================

-- =====================================================
-- PARTE 2: TABELA TBUSUARIO_APP (Nova)
-- Relacionamento N:N entre Usuário e Aplicação
-- Define qual perfil o usuário tem em cada app
-- =====================================================
-- Estrutura já existente no banco:

-- create table public.tbusuario_app (
--   usuarioapp_id bigint generated by default as identity not null,
--   usuario_id integer not null,
--   app_id integer not null,
--   perfil_id integer not null,
--   created_at timestamp without time zone not null default (now() AT TIME ZONE 'America/Fortaleza'::text),
--   created_by uuid not null,
--   updated_at timestamp without time zone null,
--   updated_by uuid null,
--   deleted_at timestamp without time zone null,
--   deleted_by timestamp without time zone null,
--   deletado public.deletado null default 'N'::deletado,
--   constraint tbusuario_app_pkey primary key (usuarioapp_id),
--   constraint tbusuario_app_usuarioapp_id_key unique (usuarioapp_id),
--   constraint tbusuario_app_created_by_fkey foreign KEY (created_by) references auth.users (id),
--   constraint tbusuario_app_perfil_id_fkey foreign KEY (perfil_id) references tbperfil (perfil_id),
--   constraint tbusuario_app_app_id_fkey foreign KEY (app_id) references tbapp (app_id),
--   constraint tbusuario_app_updated_by_fkey foreign KEY (updated_by) references auth.users (id),
--   constraint tbusuario_app_usuario_id_fkey foreign KEY (usuario_id) references tbusuario (usuario_id)
-- ) TABLESPACE pg_default;

-- =====================================================
-- PARTE 3: TABELA TBPERFIL
-- Estrutura já existente no banco:
-- =====================================================

-- create table public.tbperfil (
--   perfil_id integer generated by default as identity not null,
--   perfil text not null,
--   observacao text null,
--   created_at timestamp without time zone not null default (now() AT TIME ZONE 'America/Fortaleza'::text),
--   created_by uuid not null,
--   updated_at timestamp without time zone null,
--   updated_by uuid null,
--   deleted_at timestamp without time zone null,
--   deleted_by uuid null,
--   deletado public.deletado not null default 'N'::deletado,
--   app_id integer null,
--   constraint tbperfil_pkey primary key (perfil_id),
--   constraint tbperfil_perfil_id_key unique (perfil_id),
--   constraint tbperfil_app_id_fkey foreign KEY (app_id) references tbapp (app_id),
--   constraint tbperfil_created_by_fkey foreign KEY (created_by) references auth.users (id),
--   constraint tbperfil_deleted_by_fkey foreign KEY (deleted_by) references auth.users (id),
--   constraint tbperfil_updated_by_fkey foreign KEY (updated_by) references auth.users (id)
-- ) TABLESPACE pg_default;

-- =====================================================
-- PARTE 4: ALTERAÇÕES NA TBROTINA
-- Adicionar app_id para rotinas por aplicação
-- =====================================================

-- Adicionar coluna app_id se não existir
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
    AND table_name = 'tbrotina'
    AND column_name = 'app_id'
  ) THEN
    ALTER TABLE tbrotina ADD COLUMN app_id INTEGER NULL;
    ALTER TABLE tbrotina ADD CONSTRAINT tbrotina_app_fkey
      FOREIGN KEY (app_id) REFERENCES tbapp(app_id) ON DELETE CASCADE;
  END IF;
END $$;

COMMENT ON COLUMN tbrotina.app_id IS 'FK para tbapp - aplicação a que esta rotina pertence. NULL = rotina global.';

-- Índice para busca de rotinas por app
CREATE INDEX IF NOT EXISTS idx_tbrotina_app ON tbrotina(app_id) WHERE deletado = 'N';

-- Atualizar constraint única: mesma rotina não pode repetir na mesma app
DO $$
BEGIN
  -- Remover constraint antiga se existir
  IF EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'tbrotina_rotina_unique'
  ) THEN
    ALTER TABLE tbrotina DROP CONSTRAINT tbrotina_rotina_unique;
  END IF;

  -- Criar nova constraint com app_id
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'tbrotina_app_rotina_unique'
  ) THEN
    ALTER TABLE tbrotina ADD CONSTRAINT tbrotina_app_rotina_unique UNIQUE (app_id, rotina);
  END IF;
END $$;

-- =====================================================
-- PARTE 5: ALTERAÇÕES NA TBPERFIL_ROTINA
-- Adicionar app_id para consistência
-- =====================================================

-- Adicionar coluna app_id se não existir
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
    AND table_name = 'tbperfil_rotina'
    AND column_name = 'app_id'
  ) THEN
    ALTER TABLE tbperfil_rotina ADD COLUMN app_id INTEGER NULL;
    ALTER TABLE tbperfil_rotina ADD CONSTRAINT tbperfil_rotina_app_fkey
      FOREIGN KEY (app_id) REFERENCES tbapp(app_id) ON DELETE CASCADE;
  END IF;
END $$;

COMMENT ON COLUMN tbperfil_rotina.app_id IS 'FK para tbapp - aplicação (denormalizado para performance). Deve ser igual ao app_id do perfil.';

-- Índice para busca de permissões por app
CREATE INDEX IF NOT EXISTS idx_tbperfil_rotina_app ON tbperfil_rotina(app_id) WHERE deletado = 'N';

-- Índice composto para consulta de permissão (otimização principal)
-- CORRIGIDO: Removida coluna 'rotina' que não existe em tbperfil_rotina
DROP INDEX IF EXISTS idx_tbperfil_rotina_lookup;
CREATE INDEX idx_tbperfil_rotina_lookup
  ON tbperfil_rotina(app_id, perfil_id, rotina_id, acesso)
  WHERE deletado = 'N';

-- =====================================================
-- PARTE 6: RLS PARA TBUSUARIO_APP
-- =====================================================

ALTER TABLE tbusuario_app ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbusuario_app FORCE ROW LEVEL SECURITY;

-- SELECT: Usuário pode ver seus próprios acessos ou admin vê todos
CREATE POLICY tbusuario_app_select_policy ON tbusuario_app
  FOR SELECT TO authenticated
  USING (
    deletado = 'N'
    AND (
      -- Usuário vê seus próprios acessos
      usuario_id = (SELECT usuario_id FROM tbusuario WHERE user_id = auth.uid() AND deletado = 'N' LIMIT 1)
      -- OU é admin (pode ver todos)
      OR is_admin()
    )
  );

-- INSERT: Apenas admin pode dar acesso a apps
CREATE POLICY tbusuario_app_insert_policy ON tbusuario_app
  FOR INSERT TO authenticated
  WITH CHECK (is_admin());

-- UPDATE: Apenas admin pode alterar acessos
CREATE POLICY tbusuario_app_update_policy ON tbusuario_app
  FOR UPDATE TO authenticated
  USING (deletado = 'N' AND is_admin())
  WITH CHECK (is_admin());

-- DELETE: Apenas admin pode remover acessos
CREATE POLICY tbusuario_app_delete_policy ON tbusuario_app
  FOR DELETE TO authenticated
  USING (deletado = 'N' AND is_admin());

-- =====================================================
-- PARTE 7: RLS ATUALIZADA PARA TBAPP
-- =====================================================

ALTER TABLE tbapp ENABLE ROW LEVEL SECURITY;
ALTER TABLE tbapp FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tbapp_select_policy ON tbapp;
DROP POLICY IF EXISTS tbapp_insert_policy ON tbapp;
DROP POLICY IF EXISTS tbapp_update_policy ON tbapp;
DROP POLICY IF EXISTS tbapp_delete_policy ON tbapp;

-- SELECT: Usuário vê apenas as apps que tem acesso
CREATE POLICY tbapp_select_policy ON tbapp
  FOR SELECT TO authenticated
  USING (
    deletado = 'N'
    AND (
      -- Usuário tem acesso a esta app
      EXISTS (
        SELECT 1 FROM tbusuario_app ua
        INNER JOIN tbusuario u ON u.usuario_id = ua.usuario_id
        WHERE u.user_id = auth.uid()
          AND u.deletado = 'N'
          AND ua.app_id = tbapp.app_id
          AND ua.deletado = 'N'
      )
      -- OU é admin global
      OR is_admin()
    )
  );

-- INSERT/UPDATE/DELETE: Apenas admin
CREATE POLICY tbapp_insert_policy ON tbapp
  FOR INSERT TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY tbapp_update_policy ON tbapp
  FOR UPDATE TO authenticated
  USING (deletado = 'N' AND is_admin())
  WITH CHECK (is_admin());

CREATE POLICY tbapp_delete_policy ON tbapp
  FOR DELETE TO authenticated
  USING (deletado = 'N' AND is_admin());

-- =====================================================
-- PARTE 8: RLS ATUALIZADA PARA TBPERFIL (com app_id)
-- =====================================================

DROP POLICY IF EXISTS tbperfil_select_policy ON tbperfil;
DROP POLICY IF EXISTS tbperfil_insert_policy ON tbperfil;
DROP POLICY IF EXISTS tbperfil_update_policy ON tbperfil;
DROP POLICY IF EXISTS tbperfil_delete_policy ON tbperfil;

-- SELECT: Usuário vê perfis das apps que tem acesso
CREATE POLICY tbperfil_select_policy ON tbperfil
  FOR SELECT TO authenticated
  USING (
    deletado = 'N'
    AND (
      -- Perfil global (app_id IS NULL)
      app_id IS NULL
      -- OU usuário tem acesso à app deste perfil
      OR EXISTS (
        SELECT 1 FROM tbusuario_app ua
        INNER JOIN tbusuario u ON u.usuario_id = ua.usuario_id
        WHERE u.user_id = auth.uid()
          AND u.deletado = 'N'
          AND ua.app_id = tbperfil.app_id
          AND ua.deletado = 'N'
      )
      -- OU é admin global
      OR is_admin()
    )
  );

-- INSERT/UPDATE/DELETE: Apenas admin da app ou admin global
CREATE POLICY tbperfil_insert_policy ON tbperfil
  FOR INSERT TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY tbperfil_update_policy ON tbperfil
  FOR UPDATE TO authenticated
  USING (deletado = 'N' AND is_admin())
  WITH CHECK (is_admin());

CREATE POLICY tbperfil_delete_policy ON tbperfil
  FOR DELETE TO authenticated
  USING (deletado = 'N' AND is_admin());

-- =====================================================
-- PARTE 9: RLS ATUALIZADA PARA TBROTINA (com app_id)
-- =====================================================

DROP POLICY IF EXISTS tbrotina_select_policy ON tbrotina;
DROP POLICY IF EXISTS tbrotina_insert_policy ON tbrotina;
DROP POLICY IF EXISTS tbrotina_update_policy ON tbrotina;
DROP POLICY IF EXISTS tbrotina_delete_policy ON tbrotina;

-- SELECT: Usuário vê rotinas das apps que tem acesso
CREATE POLICY tbrotina_select_policy ON tbrotina
  FOR SELECT TO authenticated
  USING (
    deletado = 'N'
    AND (
      -- Rotina global (app_id IS NULL)
      app_id IS NULL
      -- OU usuário tem acesso à app desta rotina
      OR EXISTS (
        SELECT 1 FROM tbusuario_app ua
        INNER JOIN tbusuario u ON u.usuario_id = ua.usuario_id
        WHERE u.user_id = auth.uid()
          AND u.deletado = 'N'
          AND ua.app_id = tbrotina.app_id
          AND ua.deletado = 'N'
      )
      -- OU é admin global
      OR is_admin()
    )
  );

-- INSERT/UPDATE/DELETE: Apenas admin
CREATE POLICY tbrotina_insert_policy ON tbrotina
  FOR INSERT TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY tbrotina_update_policy ON tbrotina
  FOR UPDATE TO authenticated
  USING (deletado = 'N' AND is_admin())
  WITH CHECK (is_admin());

CREATE POLICY tbrotina_delete_policy ON tbrotina
  FOR DELETE TO authenticated
  USING (deletado = 'N' AND is_admin());

-- =====================================================
-- PARTE 10: GRANTS
-- =====================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON tbusuario_app TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE tbusuario_app_usuario_app_id_seq TO authenticated;

-- =====================================================
-- PARTE 11: DIAGRAMA ER (ASCII)
-- =====================================================
--
--  ┌─────────────────┐
--  │     tbapp       │
--  ├─────────────────┤
--  │ app_id (PK)     │◄─────────────────────────────────────┐
--  │ app_nome        │                                      │
--  │ deletado        │                                      │
--  └─────────────────┘                                      │
--          │                                                │
--          │ 1:N                                            │
--          ▼                                                │
--  ┌─────────────────┐         ┌─────────────────┐          │
--  │    tbperfil     │         │   tbusuario     │          │
--  ├─────────────────┤         ├─────────────────┤          │
--  │ perfil_id (PK)  │◄───┐    │ usuario_id (PK) │◄───┐     │
--  │ app_id (FK)     │────┘    │ user_id (UUID)  │    │     │
--  │ perfil          │    │    │ login           │    │     │
--  │ deletado        │    │    │ deletado        │    │     │
--  └─────────────────┘    │    └─────────────────┘    │     │
--          │              │                           │     │
--          │ 1:N          │                           │     │
--          ▼              │                           │     │
--  ┌─────────────────┐    │    ┌─────────────────────────┐  │
--  │    tbrotina     │    │    │    tbusuario_app        │  │
--  ├─────────────────┤    │    ├─────────────────────────┤  │
--  │ rotina_id (PK)  │    │    │ usuario_app_id (PK)     │  │
--  │ app_id (FK)     │────┘    │ usuario_id (FK) ────────┼──┘
--  │ rotina          │         │ app_id (FK) ────────────┼──┘
--  │ deletado        │         │ perfil_id (FK)          │
--  └─────────────────┘         │ ativo                   │
--          │                   │ deletado                │
--          │ N:N               └─────────────────────────┘
--          ▼
--  ┌─────────────────────────┐
--  │   tbperfil_rotina       │
--  ├─────────────────────────┤
--  │ perfil_rotina_id (PK)   │
--  │ perfil_id (FK)          │
--  │ rotina_id (FK)          │
--  │ app_id (FK)             │
--  │ rotina (denorm)         │
--  │ acesso ('S'/'N')        │
--  │ deletado                │
--  └─────────────────────────┘
--
-- =====================================================
-- FIM DO SCRIPT
-- =====================================================
