-- ============================================================================
-- CORREÇÃO DE SEQUÊNCIAS (IDENTITY)
-- ============================================================================
-- Este script corrige as sequências de todas as tabelas que usam
-- GENERATED BY DEFAULT AS IDENTITY para evitar erros de chave duplicada.
--
-- PROBLEMA:
-- Quando registros são inseridos manualmente com IDs específicos (ex: turno_id = 1),
-- a sequência não é atualizada automaticamente. Isso causa erro de chave duplicada
-- quando o sistema tenta inserir um novo registro usando a sequência.
--
-- SOLUÇÃO:
-- Este script sincroniza todas as sequências com o maior ID existente em cada tabela.
--
-- QUANDO EXECUTAR:
-- - Após importar dados manualmente
-- - Após restaurar backup
-- - Após qualquer operação que insira registros com IDs específicos
-- - Como parte da rotina de manutenção do banco
-- ============================================================================

-- Função auxiliar para corrigir sequência de uma tabela
CREATE OR REPLACE FUNCTION fix_sequence(
  p_table_name TEXT,
  p_id_column TEXT,
  p_sequence_name TEXT
) RETURNS BIGINT AS $$
DECLARE
  v_max_id BIGINT;
  v_new_value BIGINT;
BEGIN
  -- Buscar o maior ID da tabela
  EXECUTE format('SELECT COALESCE(MAX(%I), 0) FROM %I', p_id_column, p_table_name)
  INTO v_max_id;
  
  -- Definir próximo valor da sequência (max_id + 1)
  v_new_value := v_max_id + 1;
  
  -- Atualizar sequência (false = não marcar como "called", então próximo nextval retorna este valor)
  PERFORM setval(p_sequence_name, v_new_value, false);
  
  RAISE NOTICE 'Tabela %: max_id=%, próximo valor da sequência=%', p_table_name, v_max_id, v_new_value;
  
  RETURN v_new_value;
END;
$$ LANGUAGE plpgsql;

-- Corrigir todas as sequências
DO $$
BEGIN
  RAISE NOTICE '=== Iniciando correção de sequências ===';
  
  -- Tabelas com IDENTITY
  PERFORM fix_sequence('tbdepartamento', 'departamento_id', 'tbdepartamento_departamento_id_seq');
  PERFORM fix_sequence('tblinhaproducao', 'linhaproducao_id', 'tblinha_producao_linhaproducao_id_seq');
  PERFORM fix_sequence('tbvelocidadenominal', 'velocidade_id', 'tbvelocidadenominal_velocidade_id_seq');
  PERFORM fix_sequence('tbturno', 'turno_id', 'tbturno_turno_id_seq');
  PERFORM fix_sequence('tbusuario', 'usuario_id', 'tbusuario_usuario_id_seq');
  PERFORM fix_sequence('tbproduto', 'produto_id', 'tbproduto_produto_id_seq');
  PERFORM fix_sequence('tbfuncionario', 'funcionario_id', 'tbfuncionario_funcionario_id_seq');
  PERFORM fix_sequence('tbcargo', 'cargo_id', 'tbcargo_cargo_id_seq');
  PERFORM fix_sequence('tbfuncao', 'funcao_id', 'tbfuncao_funcao_id_seq');
  PERFORM fix_sequence('tblotacao', 'lotacao_id', 'tblotacao_lotacao_id_seq');
  PERFORM fix_sequence('tbempresa', 'empresa_id', 'tbempresa_empresa_id_seq');
  PERFORM fix_sequence('tbuf', 'uf_id', 'tbuf_uf_id_seq');
  PERFORM fix_sequence('tbcidade', 'cidade_id', 'tbcidade_cidade_id_seq');
  PERFORM fix_sequence('tbescolaridade', 'escolaridade_id', 'tbescolaridade_escolaridade_id_seq');
  PERFORM fix_sequence('tbestadocivil', 'estadocivil_id', 'tbestadocivil_estadocivil_id_seq');
  PERFORM fix_sequence('tbtipoadmissao', 'tipoadmissao_id', 'tbtipoadmissao_tipoadmissao_id_seq');
  PERFORM fix_sequence('tbtipoadmissaoesocial', 'tipoadmissaoesocial_id', 'tbtipoadmissaoesocial_tipoadmissaoesocial_id_seq');
  PERFORM fix_sequence('tbtipovinculo', 'tipovinculo_id', 'tbtipovinculo_tipovinculo_id_seq');
  PERFORM fix_sequence('tbcorrida', 'corrida_id', 'tbcorrida_corrida_id_seq');
  PERFORM fix_sequence('tboee_turno', 'oeeturno_id', 'tboee_turno_oeeturno_id_seq');
  
  RAISE NOTICE '=== Correção de sequências concluída ===';
END $$;

-- Comentário sobre a função
COMMENT ON FUNCTION fix_sequence(TEXT, TEXT, TEXT) IS 
'Corrige a sequência de uma tabela para evitar erros de chave duplicada. 
Sincroniza a sequência com o maior ID existente na tabela.
Parâmetros: nome_tabela, nome_coluna_id, nome_sequencia';

