-- =====================================================
-- TABELA: tboee_producao
-- Descrição: Apontamentos de produção por intervalo
--            de tempo durante o turno OEE
-- Projeto: Sistema OEE para SicFar
-- Data: 2025-12-17
-- Autor: Emanuel Silva
-- =====================================================

CREATE TABLE public.tboee_producao (
  -- Chave primária
  producao_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  -- Relacionamentos
  oeeturno_id BIGINT NOT NULL,
  linha_id INTEGER NOT NULL,
  produto_id INTEGER NOT NULL,
  turno_id INTEGER NOT NULL,

  -- Dados do apontamento
  data_apontamento DATE NOT NULL,
  hora_inicio TIME WITHOUT TIME ZONE NOT NULL,
  hora_fim TIME WITHOUT TIME ZONE NULL,

  -- Métricas de produção
  quantidade_produzida INTEGER NOT NULL,
  velocidade_nominal DECIMAL(10,2) NOT NULL,
  tempo_operacao DECIMAL(10,2) NOT NULL,
  tempo_disponivel DECIMAL(10,2) NOT NULL,

  -- Dados descritivos (desnormalização para performance)
  linha_nome TEXT NOT NULL,
  setor TEXT NOT NULL,
  sku_codigo TEXT NOT NULL,
  produto_descricao TEXT NOT NULL,
  turno_nome TEXT NOT NULL,

  -- Auditoria ALCOA+
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'America/Fortaleza'),
  created_by INTEGER NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
  updated_by INTEGER NULL,
  deleted_at TIMESTAMP WITHOUT TIME ZONE NULL,
  deleted_by INTEGER NULL,
  deletado TEXT NULL DEFAULT 'N',

  -- Constraints
  CONSTRAINT tboee_producao_pkey PRIMARY KEY (producao_id),
  CONSTRAINT tboee_producao_oeeturno_id_fkey FOREIGN KEY (oeeturno_id)
    REFERENCES tboee_turno (oeeturno_id),
  CONSTRAINT tboee_producao_linha_id_fkey FOREIGN KEY (linha_id)
    REFERENCES tblinha (linhaid),
  CONSTRAINT tboee_producao_produto_id_fkey FOREIGN KEY (produto_id)
    REFERENCES tbproduto (produto_id),
  CONSTRAINT tboee_producao_turno_id_fkey FOREIGN KEY (turno_id)
    REFERENCES tbturno (turno_id),
  CONSTRAINT tboee_producao_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES tbusuario (usuario_id),
  CONSTRAINT tboee_producao_updated_by_fkey FOREIGN KEY (updated_by)
    REFERENCES tbusuario (usuario_id),
  CONSTRAINT tboee_producao_deleted_by_fkey FOREIGN KEY (deleted_by)
    REFERENCES tbusuario (usuario_id),

  -- Validações
  CONSTRAINT tboee_producao_quantidade_check CHECK (quantidade_produzida >= 0),
  CONSTRAINT tboee_producao_velocidade_check CHECK (velocidade_nominal > 0),
  CONSTRAINT tboee_producao_tempo_operacao_check CHECK (tempo_operacao >= 0),
  CONSTRAINT tboee_producao_deletado_check CHECK (deletado IN ('S', 'N'))
) TABLESPACE pg_default;

-- =====================================================
-- ÍNDICES
-- =====================================================

-- Busca por turno OEE
CREATE INDEX idx_oee_producao_oeeturno
  ON tboee_producao(oeeturno_id)
  WHERE deletado = 'N';

-- Busca por data e turno (relatórios diários)
CREATE INDEX idx_oee_producao_data_turno
  ON tboee_producao(data_apontamento, turno_id)
  WHERE deletado = 'N';

-- Busca por linha e SKU (cálculo OEE por linha)
CREATE INDEX idx_oee_producao_linha_sku
  ON tboee_producao(linha_id, sku_codigo)
  WHERE deletado = 'N';

-- Ordenação cronológica
CREATE INDEX idx_oee_producao_created_at
  ON tboee_producao(created_at);

-- =====================================================
-- COMENTÁRIOS
-- =====================================================

COMMENT ON TABLE tboee_producao IS
  'Apontamentos de produção por intervalo de tempo durante o turno OEE';

COMMENT ON COLUMN tboee_producao.oeeturno_id IS
  'Relacionamento com cabeçalho do turno OEE';

COMMENT ON COLUMN tboee_producao.quantidade_produzida IS
  'Quantidade produzida no período (unidades)';

COMMENT ON COLUMN tboee_producao.velocidade_nominal IS
  'Velocidade nominal do SKU em unidades/hora';

COMMENT ON COLUMN tboee_producao.tempo_operacao IS
  'Tempo de operação do período em horas (hora_fim - hora_inicio)';

COMMENT ON COLUMN tboee_producao.tempo_disponivel IS
  'Tempo disponível do turno em horas (geralmente 12h)';

COMMENT ON COLUMN tboee_producao.linha_nome IS
  'Nome da linha (desnormalizado para performance)';

COMMENT ON COLUMN tboee_producao.sku_codigo IS
  'Código do SKU (desnormalizado para histórico imutável - ALCOA+)';

COMMENT ON COLUMN tboee_producao.deletado IS
  'Flag de exclusão lógica: S (excluído) ou N (ativo)';
