-- =====================================================
-- TABELA: tboee_paradas
-- Descrição: Apontamentos de paradas de produção
--            (estratégicas, planejadas e não planejadas)
-- Projeto: Sistema OEE para SicFar
-- Data: 2025-12-17
-- Autor: Emanuel Silva
-- =====================================================

CREATE TABLE public.tboee_paradas (
  -- Chave primária
  parada_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  -- Relacionamentos
  oeeturno_id BIGINT NOT NULL,
  linha_id INTEGER NOT NULL,
  turno_id INTEGER NOT NULL,
  codigoparada_id INTEGER NULL,
  lote_id INTEGER NULL,

  -- Dados da parada
  data_parada DATE NOT NULL,
  hora_inicio TIME WITHOUT TIME ZONE NOT NULL,
  hora_fim TIME WITHOUT TIME ZONE NULL,
  duracao_minutos INTEGER NULL,

  -- Classificação da parada
  tipo_parada TEXT NOT NULL,
  codigo_parada TEXT NOT NULL,
  descricao_parada TEXT NOT NULL,
  impacta_disponibilidade BOOLEAN DEFAULT TRUE,

  -- Dados descritivos
  linha_nome TEXT NOT NULL,
  turno_nome TEXT NOT NULL,
  observacao TEXT NULL,

  -- Conferência (ALCOA+)
  conferido_por_supervisor INTEGER NULL,
  conferido_em TIMESTAMP WITHOUT TIME ZONE NULL,

  -- Auditoria ALCOA+
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'America/Fortaleza'),
  created_by INTEGER NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
  updated_by INTEGER NULL,
  deleted_at TIMESTAMP WITHOUT TIME ZONE NULL,
  deleted_by INTEGER NULL,
  deletado TEXT NULL DEFAULT 'N',

  -- Constraints
  CONSTRAINT tboee_paradas_pkey PRIMARY KEY (parada_id),
  CONSTRAINT tboee_paradas_oeeturno_id_fkey FOREIGN KEY (oeeturno_id)
    REFERENCES tboee_turno (oeeturno_id),
  CONSTRAINT tboee_paradas_linha_id_fkey FOREIGN KEY (linha_id)
    REFERENCES tblinha (linhaid),
  CONSTRAINT tboee_paradas_turno_id_fkey FOREIGN KEY (turno_id)
    REFERENCES tbturno (turno_id),
  CONSTRAINT tboee_paradas_codigoparada_id_fkey FOREIGN KEY (codigoparada_id)
    REFERENCES tbcodigoparada (codigoparada_id),
  CONSTRAINT tboee_paradas_lote_id_fkey FOREIGN KEY (lote_id)
    REFERENCES tblote (lote_id),
  CONSTRAINT tboee_paradas_conferido_por_fkey FOREIGN KEY (conferido_por_supervisor)
    REFERENCES tbusuario (usuario_id),
  CONSTRAINT tboee_paradas_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES tbusuario (usuario_id),
  CONSTRAINT tboee_paradas_updated_by_fkey FOREIGN KEY (updated_by)
    REFERENCES tbusuario (usuario_id),
  CONSTRAINT tboee_paradas_deleted_by_fkey FOREIGN KEY (deleted_by)
    REFERENCES tbusuario (usuario_id),

  -- Validações
  CONSTRAINT tboee_paradas_tipo_check CHECK (tipo_parada IN ('ESTRATEGICA', 'PLANEJADA', 'NAO_PLANEJADA')),
  CONSTRAINT tboee_paradas_duracao_check CHECK (duracao_minutos IS NULL OR duracao_minutos >= 0),
  CONSTRAINT tboee_paradas_deletado_check CHECK (deletado IN ('S', 'N'))
) TABLESPACE pg_default;

-- =====================================================
-- ÍNDICES
-- =====================================================

-- Busca por turno OEE
CREATE INDEX idx_oee_paradas_oeeturno
  ON tboee_paradas(oeeturno_id)
  WHERE deletado = 'N';

-- Busca por data e turno
CREATE INDEX idx_oee_paradas_data_turno
  ON tboee_paradas(data_parada, turno_id)
  WHERE deletado = 'N';

-- Busca por linha (cálculo OEE)
CREATE INDEX idx_oee_paradas_linha
  ON tboee_paradas(linha_id)
  WHERE deletado = 'N';

-- Busca por tipo de parada
CREATE INDEX idx_oee_paradas_tipo
  ON tboee_paradas(tipo_parada)
  WHERE deletado = 'N';

-- Busca por código de parada
CREATE INDEX idx_oee_paradas_codigo
  ON tboee_paradas(codigo_parada)
  WHERE deletado = 'N';

-- Ordenação cronológica
CREATE INDEX idx_oee_paradas_created_at
  ON tboee_paradas(created_at);

-- =====================================================
-- COMENTÁRIOS
-- =====================================================

COMMENT ON TABLE tboee_paradas IS
  'Apontamentos de paradas de produção (estratégicas, planejadas e não planejadas)';

COMMENT ON COLUMN tboee_paradas.duracao_minutos IS
  'Duração da parada em minutos (calculado automaticamente: hora_fim - hora_inicio)';

COMMENT ON COLUMN tboee_paradas.impacta_disponibilidade IS
  'Se FALSE, parada afeta Performance (paradas < 10 min). Se TRUE, afeta Disponibilidade.';

COMMENT ON COLUMN tboee_paradas.tipo_parada IS
  'Tipos: ESTRATEGICA (não entra no OEE) | PLANEJADA (reduz Disponibilidade) | NAO_PLANEJADA (reduz Disponibilidade)';

COMMENT ON COLUMN tboee_paradas.conferido_por_supervisor IS
  'ID do supervisor que conferiu a parada (ALCOA+: Atribuível e Completo)';

COMMENT ON COLUMN tboee_paradas.conferido_em IS
  'Data/hora em que o supervisor conferiu a parada (ALCOA+: Contemporâneo)';

COMMENT ON COLUMN tboee_paradas.codigo_parada IS
  'Código alfanumérico da parada para busca rápida (ex: MAQ-001, INS-045)';

COMMENT ON COLUMN tboee_paradas.descricao_parada IS
  'Descrição detalhada da parada (ex: "Quebra do motor principal", "Falta de matéria-prima")';

COMMENT ON COLUMN tboee_paradas.codigoparada_id IS
  'FK para tbcodigoparada. NULL se código de parada não estiver cadastrado no sistema.';

COMMENT ON COLUMN tboee_paradas.lote_id IS
  'FK para tblote. NULL se parada não estiver associada a um lote específico.';

COMMENT ON COLUMN tboee_paradas.deletado IS
  'Flag de exclusão lógica: S (excluído) ou N (ativo)';
