-- =====================================================
-- TABELA: tboee_perdas
-- Descrição: Apontamentos de perdas de qualidade
--            (unidades rejeitadas/descartadas)
-- Componente OEE afetado: Qualidade_Unidades
-- Projeto: Sistema OEE para SicFar
-- Data: 2025-12-17
-- Autor: Emanuel Silva
-- =====================================================

CREATE TABLE public.tboee_perdas (
  -- Chave primária
  perdas_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

  -- Relacionamentos
  oeeturno_id BIGINT NOT NULL,
  producao_id BIGINT NOT NULL,
  linha_id INTEGER NOT NULL,
  turno_id INTEGER NOT NULL,

  -- Dados da perda
  data_apontamento DATE NOT NULL,
  unidades_rejeitadas INTEGER NOT NULL,
  motivo_rejeicao TEXT NOT NULL,
  observacao TEXT NULL,

  -- Dados descritivos
  linha_nome TEXT NOT NULL,
  turno_nome TEXT NOT NULL,

  -- Auditoria ALCOA+
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'America/Fortaleza'),
  created_by INTEGER NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
  updated_by INTEGER NULL,
  deleted_at TIMESTAMP WITHOUT TIME ZONE NULL,
  deleted_by INTEGER NULL,
  deletado TEXT NULL DEFAULT 'N',

  -- Constraints
  CONSTRAINT tboee_perdas_pkey PRIMARY KEY (perdas_id),
  CONSTRAINT tboee_perdas_oeeturno_id_fkey FOREIGN KEY (oeeturno_id)
    REFERENCES tboee_turno (oeeturno_id),
  CONSTRAINT tboee_perdas_producao_id_fkey FOREIGN KEY (producao_id)
    REFERENCES tboee_producao (producao_id),
  CONSTRAINT tboee_perdas_linha_id_fkey FOREIGN KEY (linha_id)
    REFERENCES tblinha (linhaid),
  CONSTRAINT tboee_perdas_turno_id_fkey FOREIGN KEY (turno_id)
    REFERENCES tbturno (turno_id),
  CONSTRAINT tboee_perdas_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES tbusuario (usuario_id),
  CONSTRAINT tboee_perdas_updated_by_fkey FOREIGN KEY (updated_by)
    REFERENCES tbusuario (usuario_id),
  CONSTRAINT tboee_perdas_deleted_by_fkey FOREIGN KEY (deleted_by)
    REFERENCES tbusuario (usuario_id),

  -- Validações
  CONSTRAINT tboee_perdas_unidades_check CHECK (unidades_rejeitadas > 0),
  CONSTRAINT tboee_perdas_deletado_check CHECK (deletado IN ('S', 'N'))
) TABLESPACE pg_default;

-- =====================================================
-- ÍNDICES
-- =====================================================

-- Busca por turno OEE
CREATE INDEX idx_oee_perdas_oeeturno
  ON tboee_perdas(oeeturno_id)
  WHERE deletado = 'N';

-- Busca por apontamento de produção
CREATE INDEX idx_oee_perdas_producao
  ON tboee_perdas(producao_id)
  WHERE deletado = 'N';

-- Busca por data e turno
CREATE INDEX idx_oee_perdas_data_turno
  ON tboee_perdas(data_apontamento, turno_id)
  WHERE deletado = 'N';

-- Busca por linha
CREATE INDEX idx_oee_perdas_linha
  ON tboee_perdas(linha_id)
  WHERE deletado = 'N';

-- Ordenação cronológica
CREATE INDEX idx_oee_perdas_created_at
  ON tboee_perdas(created_at);

-- =====================================================
-- COMENTÁRIOS
-- =====================================================

COMMENT ON TABLE tboee_perdas IS
  'Apontamentos de perdas de qualidade (unidades rejeitadas/descartadas). Afeta componente Qualidade_Unidades do OEE.';

COMMENT ON COLUMN tboee_perdas.unidades_rejeitadas IS
  'Quantidade de unidades descartadas/refugadas (deve ser > 0)';

COMMENT ON COLUMN tboee_perdas.motivo_rejeicao IS
  'Motivo da rejeição das unidades (ex: "Fora de especificação - pH", "Contaminação microbiológica", "Embalagem danificada")';

COMMENT ON COLUMN tboee_perdas.producao_id IS
  'FK para tboee_producao. Vincula a perda ao apontamento de produção correspondente.';

COMMENT ON COLUMN tboee_perdas.observacao IS
  'Observações adicionais sobre a perda (ex: número do lote afetado, ações corretivas tomadas)';

COMMENT ON COLUMN tboee_perdas.deletado IS
  'Flag de exclusão lógica: S (excluído) ou N (ativo)';

-- =====================================================
-- INTEGRAÇÃO COM TOTVS (Comentário informativo)
-- =====================================================

COMMENT ON TABLE tboee_perdas IS
  'IMPORTANTE: Perdas devem ser sincronizadas com TOTVS (ERP) conforme Atividade 07.
   Fluxo: SicFar → Dossiê de Produção → TOTVS.
   Validação cruzada obrigatória entre SicFar e TOTVS para conformidade BPF.';
